_target_: reinforcement_learning.DQN_util.DQNAgent_CNN

# Parameters for DQN Agent
# Exploration rate
epsilon: 0.8
epsilon_decay: 0.99995
epsilon_min: 0.1
supervisor_epsilon: 0.5

# Pretrained weights
weights_dir: "models/best/CNN" # needs to be manually created
weights_path: "" # example: "dqn_CNN_episode_1000" without .index or .data-00000-of-00001
use_pretrained_best_model: False
auto_set_epsilon: False

# Model parameters
action_dim: 4
input_shape: [84, 84, 7] # 7: 3 RGB, 3 depth, 1 one-hot-encoded TCP
learning_rate: 0.00025

# Q-Value calculation
gamma: 0.99