_target_: reinforcement_learning.DQN_util.DQNAgent_FCN

# Parameters for DQN Agent
# Exploration rate
epsilon: 0.8
epsilon_decay: 0.99995
epsilon_min: 0.1
supervisor_epsilon: 0.5

# Pretrained weights
weights_dir: "models/best/FCN" # needs to be manually created
weights_path: "" # example: "dqn_FCN_episode_1000" without .index or .data-00000-of-00001
use_pretrained_best_model: False
auto_set_epsilon: False

# Model parameters
action_dim: 2
input_shape: [88, 88, 7] # 7: 3 RGB, 3 depth, 1 one-hot-encoded TCP
learning_rate: 0.00025

# Q-Value calculation
gamma: 0.99