defaults:
  - default_hydra_config
  - pushing_env: pushing_env
  - robot: ur10_cell

log_level: INFO
data_root: "/home/jovyan/data"

# Workspace bounds (in meters)
workspace_bounds:
  - [0.3, 0.9]   # x bounds
  - [-0.3, 0.3]  # y bounds
  - [-0.0125, 0.35] # z bounds

# Movement bounds (in meters)
# Movement bounds need to match the orthographic bounds of the camera
# find in teletentric_camera_config.yaml
# Center of the Camera is at x=0.6, y=0.0, z=0.1
movement_bounds:
  - [0.15, 1.05]  # x bounds
  - [-0.45, 0.45]  # y bounds
  - [-0.5, 0.5]  # z bounds

# Gripper configuration  
gripper_offset:
  translation: [0, 0, 0]
  rotation: [3.14159265359, 0, 1.57079632679]

# Fixed z height for the gripper floating above the table
fixed_z_height: 0.005
