defaults:
  - default_hydra_config
  - default_workspace_bounds
  - default_movement_bounds
  - default_gripper_offset
  - default_fixed_z_height
  - pushing_env: pushing_env
  - robot: ur10_cell

log_level: INFO
data_root: "/home/jovyan/data"


