defaults:
  - defaults
  - task_factory: simple_push_task
  - camera_factory: static
  - teletentric_camera: ../teletentric_camera_config
  - _self_

log_level: DEBUG # INFO, DEBUG, WARN, ERROR

debug: true
render: true

projection_resolution: [512, 512]

# Gripper configuration  
gripper_offset:
  translation: [0, 0, 0]
  rotation: [3.14159265359, 0, 1.57079632679]

fixed_z_height: 0.005

# Workspace bounds (in meters)
workspace_bounds:
  - [0.35, 0.85]   # x bounds
  - [-0.25, 0.25]  # y bounds
  - [-0.0125, 0.35] # z bounds

# Movement bounds (in meters)
movement_bounds:
  - [0.2, 1.0]  # x bounds
  - [-0.4, 0.4]  # y bounds
  - [-0.5, 0.5]  # z bounds


# Step size relative to the workspace bounds, old value: 0.4, now it is 1 and i like better
step_size: 1

# Movement condition
absolut_movement: False

# Threshold for no movement punishment
no_movement_threshold: 0.02

# Reward
distance_obj_area_reward_scale: 1000
distance_TCP_obj_reward_scale: 25           # Faustregel: Faktor 20-50 kleiner als distance_obj_area_reward_scale
iou_reward_scale: 2000
max_moves_without_positive_reward: 3

# Training parameters
num_envs: 1
num_episodes: 500    #10000
max_steps_per_episode: 200 #200
batch_size: 16
target_update_freq: 100
save_freq: 10
learning_rate: 0.00005          # old value: 0.00025, trying a lower value now as the net seems to adpat too fast and be stuck at -1,-1
use_pretrained_best_model: False

# Load pretrained model
weights_dir: "models/best"
weights_path: ""

# Model parameters
model_dir: "models/dqn"
model_path: "models/dqn/dqn_episode_final"

# Plotting parameters (reward and epsilon)
plot_freq: 3
plot_dir: "models/plot"

# Testing parameters
num_test_episodes: 10
render_delay: 50  # milliseconds between frames

# Camera settings
camera:
  image_size: [84, 84]  # Standard size for DQN input
  orthographic: true

# Supervisor settings
supervisor:
  sv_90deg_movement_threshold: 0.1      # 0.1 seems to be a good value, as most objects are smaller than 0.1m;   <0.1 is getting more aggressive with pushing and less "circling" around the object 

# Environment settings
env:
  _target_: bullet_env.pushing_env.PushingEnv  # Make sure this points to PushingEnv
  bullet_client: ${bullet_client}
  robot: ${robot}
  task_factory: ${task_factory}
  teletentric_camera: ${teletentric_camera}
  workspace_bounds: ${workspace_bounds}
  movement_bounds: ${movement_bounds}
  success_threshold_trans: 0.05
  succes_threshold_rot: 20.0
  max_steps: 200
  coordinate_axes_urdf_path: null
#  step_size: 0.1
