defaults:
  - defaults
  - task_factory: simple_push_task
  - camera_factory: static
  - teletentric_camera: ../camera_factory/teletentric_camera_config
  - _self_

# Switch modes
debug: true
render: true

# Environment parameters
auto_mode: false # False: manual mode with keyboard, True: auto mode with automatic movement from object to area

# Camera parameters
projection_resolution: [512, 512]

# Set training to False to play the game
pushing_env:
  training: False # do not change!
