_target_: bullet_env.teletentric_camera.TeletentricCamera
height: 0.1
resolution: [500, 500]
intrinsics:
  - 714.29 # 642.730
  - 0.0
  - 250.0
  - 0.0
  - 714.29 # 642.730
  - 250.0
  - 0.0
  - 0.0
  - 1.0
depth_range:
  - 0.05  # Adjusted minimum depth range
  - 1.0   # Adjusted maximum depth range
record_depth: true
orthographic_bounds:
  left: -0.35
  right: 0.35
  bottom: -0.35
  top: 0.35
