_target_: bullet_env.teletentric_camera.TeletentricCamera
height: 0.175
resolution: [500, 500]
intrinsics:
  - 555.56 # 642.730 (v0) and for 0.35 714.29 (v1)
  - 0.0
  - 250.0
  - 0.0
  - 555.56 # 642.730 (v0) and for 0.35 714.29 (v1)
  - 250.0
  - 0.0
  - 0.0
  - 1.0
record_depth: true
orthographic_bounds:
  left: -0.45
  right: 0.45
  bottom: -0.45
  top: 0.45
