_target_: manipulation.task.simple_push_task.PushTaskFactory

n_objects: 1
min_n_objects: 1

push_object_factory:
  _target_: manipulation.task.simple_push_task.PushObjectFactory
  objects_root: ${data_root}/assets/objects
  object_types: ['cube', 'cylinder'] # remove any objects you don't want to use, empty list means all objects; possible objects: 'cross', 'cube', 'cylinder', 'double_t', 't'
push_area_factory:
  _target_: manipulation.task.simple_push_task.PushAreaFactory
  areas_root: ${data_root}/assets/areas


